### ISSUE TITLE
Problems with building power sim from scratch

### ISSUE THREAD

**Issue by psyargh** [pitakakariki/simr#102]
Hello,

I've had problems building my power simulation from scratch.  

This is my model:

    model1 <- makeLmer(y ~ (x1+x2)*x3*x4 + (1|subject) + (1|stimset) + (1|stimuli), fixef=b, VarCorr=V2, sigma=s, data=mydata)

These are the parameters I estimated:

    b <- c(1.04, 1.73, -0.17, 0.3, 0.4, 0.2, 0.3, 0.1, -0.2, -0.1, 0.3, 1.2) # fixed intercept and slope
    V2 <- matrix(c(0.12, 0.06, 0.06, 0.06, 0.12, 0.06, 0.06, 0.06, 0.12), 3) # random intercept and slope variance-covariance matrix
    s <- 0.28 # residual variance

This is the error message I received:

    Error in setParams(object, newparams) : length mismatch in theta (6!=3)

Could you please help me identify and solve the problem?

Thank you!

**Comment by pitakakariki** [comment]
You have three independent random intercepts in your formula, so `V2` should be a list of three random effect variances. e.g.:

    V2 <- list(0.12, 0.12, 0.12)

**Comment by psyargh** [comment]
Thanks! However, once I do that, I get the following error: 

Error in chol.default(V, pivot = TRUE) : 'a' must be a square matrix

**Comment by pitakakariki** [comment]
What does your `V2` look like now?

**Comment by psyargh** [comment]
Apologies-- I had retained the matrix command, but I replaced it with "list" and now it works. Thanks!

However, when I do powerSim, it gives me the power of 0% no matter was I specify as my parameters. 
Here's how it looks: 
fixef(model1) ["(x1+x2)*x3*x4"] <- 0.05
powerSim(model1, fixed("(x1+x2)*x3*x4"), nsim=10)

**Comment by pitakakariki** [comment]
You need to specify effect names like this:

    fixef(model1) ["x1"] <- ...
    fixef(model1) ["x3:x4"] <- ...

And the same applied to `fixed`. Did you not get an error from your `fixef<-` call?

**Comment by pitakakariki** [comment]
You should be okay just specifying the effect sizes you're interested in. Note that you have two 3-way interactions though, `"x1:x3:x4"` and `"x2:x3:x4"`.

**Comment by SixinLiao** [comment]
Hi, If I want to add random slops for the fixed effects, how should I create the variance-covariance matrix for the model like this: model1 <- makeLmer(y ~ (x1*x2 + (x1+ x2|subject) + (x1+x2|item)? both X1 and X2 have three levels using sliding difference contrast so it will need a 5*5 matrix? But not sure about how to set it up. Any assistance is much appreciated.
