### ISSUE TITLE
Error printing power curve

### ISSUE THREAD

**Issue by sho-87** [pitakakariki/simr#108]
```
model <- lmer(y ~ a + b + c + d + d*condition + b*condition + (1+b|id), data=df, REML=F)
fixef(model)["b:condition1"] <- -0.1
pc <- powerCurve(model, test=fixed("b:condition1", "z"), nsim=10)
```
`condition` and `id` are both factors

When I run the code above and try to `print(pc)` I get the following error:

```
Power for predictor 'b:condition1', (95% confidence interval),
by largest value of a:
Error in sprintf("%7i: ", x$xval[i]) : 
  invalid format '%7i'; use format %f, %e, %g or %a for numeric objects
```

`plot(pc)` works fine, but printing doesnt seem to work. Any idea about whats causing this?

**Comment by pitakakariki** [comment]
If you need a workaround, `summary(pc)` ought to still work.

The code assumes that the "along" variable is an integer, and falls over when it's not. It's kind of a mystery that no one found this earlier! Thanks for the bug report.

**Comment by sho-87** [comment]
`summary(pc)` seems to give some information, but I was looking at [this](https://besjournals.onlinelibrary.wiley.com/doi/abs/10.1111/2041-210X.12504) paper and looking at the example output there `print(pc)` appears to have an additional piece of information that is missing from `summary(pc)` which is the number of rows of data

Im a bit confused about what power curves are intended to show (or maybe Im misusing it). What I want to know is what sample size is required to achieve 80% power. Sample size in my case is given by `id` (each `id` is a person). How does `largest value of a` relate to sample size in this case?

**Comment by pitakakariki** [comment]
The idea is to have the x-axis for the power curve in sensible units. For example, if you have multiple observations per person, it's more useful to know how many people rather than how many observations in total.

In your case you might want to use `along="id"` as an argument to `powerCurve`. The default is the first fixed effect (i.e. `a`) but as you've noted that probably doesn't make sense for what you're trying to do.

**Comment by sho-87** [comment]
perfect, the github version prints correctly now, thanks!
