### ISSUE TITLE
Setting effect size

### ISSUE THREAD

**Issue by sho-87** [pitakakariki/simr#111]
A couple of questions about setting fixed effect sizes:

1. I'm using `fixef(model)["varA"] <- -0.1` to set the fixed effect for one of my predictors. Should this be done for all predictors in the model? Or only the one of interest?

2. What metric is the effect size in? I'd like to set a standardized effect size like a Cohen's d, but even a value like `0.1`, which is pretty small in cohen's d terms, gives me a lot of power when looking at the power curve

**Comment by pitakakariki** [comment]
1. This is probably best addressed here: https://github.com/pitakakariki/simr/issues/112

2. As far as I know, there's no standard equivalent to Cohen's d for mixed models. The effect size here is the same as given by `fixef`, so whether it's small or large depends on what scale your covariates are on.
