### ISSUE TITLE
`powerCurve` missing with no default warning message

### ISSUE THREAD

**Issue by stefanocoretta** [pitakakariki/simr#139]
When R diagnostics is on in RStudio ("Check arguments to function call" is checked), `powerCurve()` produces a warning for missing arguments, which lack defaults.

<img width="702" alt="screenshot 2018-11-05 at 08 06 51" src="https://user-images.githubusercontent.com/6429302/47982928-df10b180-e0d1-11e8-9633-8e0fe313b124.png">

**Comment by pitakakariki** [comment]
Thanks for the heads up. I'd call this a false positive, looks like RStudio is being a bit overambitious in its diagnostics. I'll keep the issue open though in case I can think of a workaround.
