### ISSUE TITLE
powerSim error: "wrong number of contrast matrix rows"

### ISSUE THREAD

**Issue by CarolYingcanWang** [pitakakariki/simr#148]
Hi Peter, 

Thanks very much for your simr package.

I have been trying the powerSim function with the following scripts:

       
         powerWord <- powerSim(modelWord, test=fixed("targetWordFactor"), nsim = 20)
         powerWord

But it gives me the following results with errors:

     Power for predictor 'targetWordFactor', (95% confidence interval):
       0.00% ( 0.00, 16.84)
 
     Test: Likelihood ratio
 
     Based on 20 simulations, (0 warnings, 20 errors)
     alpha = 0.05, nrow = NA
 
     Time elapsed: 0 h 0 m 4 s

     nb: result might be an observed power calculation

I checked that all of the 20 errors are "wrong number of contrast matrix rows". 
This is strange because the contrasts I used with the "targetWordFactor" did not cause any problem for the lmer model (modelWord). It is a 3-level default treatment contrast that looks something like this:
       

```
         b c
       a 0 0  
       b 1 0 
       c 0 1  

```

Could you tell me how I can fix this error please? 

Many thanks!!
Carol

**Comment by pitakakariki** [comment]
Does the test work outside of simr?

    drop1(modelWord, test="Chisq")

**Comment by CarolYingcanWang** [comment]
Seems like it works, here is the result to `drop1(modelWord, ``test="Chisq"):`

![screenshot 2019-01-29 at 21 42 26](https://user-images.githubusercontent.com/10388639/51942391-d0a30f00-240e-11e9-8531-8cfeb3299b4b.png)

**Comment by pitakakariki** [comment]
I'll need more information then, for example the specification of `modelWord`.

**Comment by CarolYingcanWang** [comment]
Thanks for your help! Here is the model (logRTmodelWord is what I used in my original script):
`logRTmodelWord <- lmer(logRT ~ 1 + targetWordFactor  +
                      (1+targetWordFactor|subject) + (1+targetWordFactor|item),
                    data = pauseDetValidNoFillersExcluded, REML=FALSE)`

**Comment by pitakakariki** [comment]
I'll need the bit where you specify the contrasts too.

**Comment by CarolYingcanWang** [comment]
The contrasts:
`pauseDetValidNoFillersExcluded$targetWordFactor <- factor(pauseDetValidNoFillersExcluded$targetWordFactor, c("W","WW","NW"))
contrasts(pauseDetValidNoFillersExcluded$targetWordFactor)`

**Comment by pitakakariki** [comment]
So you're not actually manually setting the contrasts?

**Comment by pitakakariki** [comment]
It's not something I've seen before, could have something to do with the singular fit.

**Comment by pitakakariki** [comment]
I can't replicate the problem. Check that you've got the latest lme4 and simr, and if it still doesn't work you'll need to send me the dataset and script.

**Comment by CarolYingcanWang** [comment]
Hi Peter,

Thank you very much for offering to help. 
I have checked that I have been using the latest lme4 and simr. Attached please find my script and dataset. You can run the script directly after setting up setwd.

Apart from the powerSim function that produces the error “wrong number of contrasts matrix row”, powerCurve function does not work with my data either and the error shows that "object 'logRT' not found”.

I would sincerely appreciate your help on this.

Many thanks,
Carol

**Comment by pitakakariki** [comment]
You can't attach files when replying to Github threads, you'll need to email the files to the address listed on CRAN.

**Comment by CarolYingcanWang** [comment]
Hi Peter, I just forwarded the files to your simr gmail. Thanks very much!

**Comment by pitakakariki** [comment]
It will take me a while to track down the actual problem, but I think it's something to do with missing values.

In the meantime, you can probably work around this by removing incomplete rows from your data before fitting the model.

**Comment by CarolYingcanWang** [comment]
Removing missing data did solve the problem! Thanks a lot for your help!
