### ISSUE TITLE
PowerCurve does not produce a curve

### ISSUE THREAD

**Issue by ediachek** [pitakakariki/simr#164]
Hi,

I am testing complex fixed effects on the data that has already been collected. Here is the model:

_m <- glmer(response.numeric ~ 1+ memory + disfluency + planning.hypothesis + pauses.ums + (1|participant_id) + (1|item), data=data,family=binomial)_

Now, I'd like to do a replication study and I want to figure out the sample size. I am using the powerCurve function. The code is below:

_c.memory <- powerCurve(m, along = "participant_id", test=fixed("memory"), nsim=100)_ 

Unfortunately, what I get is the following:

![Screen Shot 2019-09-13 at 5 27 43 PM](https://user-images.githubusercontent.com/44447574/64898206-d969ed80-d64b-11e9-9a64-22a7fd1c1785.png)

I have been trying to extend my data but I get the following error:

_> m_ext_subj <- extend(m, along="participant_id", n=20)_
Error in `levels<-.factor`(`*tmp*`, value = values) : 
  number of levels differs

I'd appreciate any suggestions on how to fix this!

**Comment by pitakakariki** [comment]
I think that might be a bug in `extend`.

Does changing `participant_id` from a factor to a character (or numeric) vector fix this?

**Comment by ediachek** [comment]
Hi Peter,

I changed participant_id to a numeric vector and this is what I am getting:

[cid:A5869E50-7369-4E20-AF7B-B2BF2E45043E@hsd1.tn.comcast.net.]

I’m not sure why it’s only showing me 20 participants (I have 102 in my data). I’m new to R, so it’s quite possible that there’s an error in my code. Here are the commands that I’m using:

data$participant_id <- as.numeric(data$participant_id)
m_ext_subj <- extend(m, along="participant_id", n=20)
c.memory <- powerCurve(m_ext_subj, along = "participant_id", test=fixed("memory"), nsim=2)

I’d appreciate any help!

-E
On Sep 16, 2019, at 4:06 PM, Peter Green <notifications@github.com<mailto:notifications@github.com>> wrote:


I think that might be a bug in extend.

Does changing participant_id from a factor to a character (or numeric) vector fix this?

**Comment by pitakakariki** [comment]
It's better to comment on github rather than reply to the notification emails. Looks like it scrubbed an attachment?

**Comment by ediachek** [comment]
Just updated the comment!

**Comment by pitakakariki** [comment]
The argument `n=20` "extends" the dataset to 20 participants (extend is a bit of a misnomer in this case). I'm not sure why you'd want to extend when your power is already high, but if you do e.g. `n=122` will add 20 participants (you might need to check with `getData` afterwards though, `extend` is fairly simpe and can unbalance your data).

Have a look at `c.memory$warnings` and `c.memory$errors` to see if any problems were logged during the simulations.

Note that if you have a large number of observations per participant you might still have high power with fewer participants.

**Comment by ediachek** [comment]
I'm trying to replicate the experiment and I'd like to see what the sample size should be to get the same effect size for multiple fixed effects.

Yes, it looks like I have high power even with as few as 30 people.

**Comment by ediachek** [comment]
Ok, I have managed to resolve the issue by: i) changing "participant_id" from a factor to numeric; 
ii) testing the fixed effect that is smaller than the original one; iii) increasing the number of simulations. Attaching the power curve for 100 simulations. 

![planning hypothesis_nsims100](https://user-images.githubusercontent.com/44447574/65298533-74bdff80-db31-11e9-8f55-f68dc747d1fc.png)
 
Thank you for your help!
