### ISSUE TITLE
Can't call individual levels of categorical fixed effect in doTest or powerSim

### ISSUE THREAD

**Issue by rosielala** [pitakakariki/simr#193]
Trying to work out the significance of an individual level (dummy variable) for a categorical fixed effect with three levels. DoTest and powerSim are throwing up errors
i.e. Error in drop1.merMod(fit, dropname, test = test) :   scope is not a subset of term labels

model_raw <- lmer(y ~ veg_cat + g + (1|x), data= RAI))

             Estimate Std. Error   t value
(Intercept) 29.103971   8.354501 3.4836276
veg_cat2     7.995011   8.782959 0.9102867
veg_cat3    45.645011  10.081791 4.5274707
g            7.025509   2.862082 2.4546842

> doTest(model_raw, fixed("veg_cat", "lr")) # 
p-value for predictor 'veg_cat': 0.0002374201
          --------------------
Test: Likelihood ratio

> doTest(model_raw, fixed("veg_cat2", "lr")) 
Error in drop1.merMod(fit, dropname, test = test) : 
  scope is not a subset of term labels

powerSim(model_raw, test= fixed("veg_cat2", "lr"))
No Power result and 
Error 
262 Testing   262 scope is not a subset of term labels
263 Testing   263 scope is not a subset of term labels
264 Testing   264 scope is not a subset of term labels
etc.

**Comment by pitakakariki** [comment]
`"lr"` isn't supported for testing individual levels - you'll need `"z"` or "`t`".

**Comment by rosielala** [comment]
Thankyou! Solved!
