### ISSUE TITLE
getData() fails when using subsets in formula

### ISSUE THREAD

**Issue by ibartomeus** [pitakakariki/simr#21]
Awesome package, thanks! 

This is not important, but when specifying the data via 'subset()' in the model, 'extend()' does not work, because 'getData()' function can't get the data. 

If fixing it is not a priority, an error message can help spotting the issue, as the actual message is not informative.

Nacho

**Comment by pitakakariki** [comment]
Thanks. There are a number of problems along the same lines, such as transformed variables not being found by `powerSim`. I'll have a think about how to handle these cases, but I think an error message might be the best option for now.

**Comment by pitakakariki** [comment]
I've had a proper look, and I think it's worth fixing this properly. There's a couple of simple ways to do it, but they might break stuff somewhere else. I'll block off some time next week and fix this (and a few other things).

**Comment by ibartomeus** [comment]
Thanks Peter!

On Thu, Oct 1, 2015 at 1:20 AM Peter <notifications@github.com> wrote:

> I've had a proper look, and I think it's worth fixing this properly.
> There's a couple of simple ways to do it, but they might break stuff
> somewhere else. I'll block off some time next week and fix this (and a few
> other things).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pitakakariki/simr/issues/21#issuecomment-144572209>.
>
-- 
-- 
Ignasi Bartomeus PhD
www.bartomeuslab.com
@ibartomeus
Skype: nachobartomeus

Dpto. Ecología Integrativa
Estación Biológica de Doñana (EBD-CSIC)
Avda. Américo Vespucio s/n
Isla de la Cartuja
41092, Sevilla (Spain)

**Comment by pitakakariki** [comment]
dev branch now has an (untested) fix for this.
