### ISSUE TITLE
new to r and simr alpha.S not found error

### ISSUE THREAD

**Issue by bidstat** [pitakakariki/simr#213]
Hi, this could be me.. I am trying to run simr in R studio for repeated measure simulation (based on Arend & Schafer's 2019 tutorial). I am trying to launch the following code to get started :

sim.ef <- powerSim(model, fixed("x", "kr"), alpha=alpha.S, nsim=10) 

but get the error message:

Error in simrOptions(...) : object 'alpha.S' not found

Is this a user error or a bug? Likely to be the former but thought I should check!
Thank you

Please note that this issue tracker is for reporting bugs in the `simr` package.

Due to time constraints I can no longer provide support for any statistical aspects of your power analysis.

However, do note that unclear usage or unhelpful documentation in `simr` is still a "bug".

If you have found a coding bug, please provide a reproducible example to help me isolate the problem.

**Comment by pitakakariki** [comment]
Looks like you've missed the step where you set `alpha.S`.
