### ISSUE TITLE
Does simr support clmm?

### ISSUE THREAD

**Issue by carlmenzies** [pitakakariki/simr#227]
Hi,

I want to work with the simr package to get powerSim and powerCurve for a study. As my data is ordinal, I'm working with a clmm. Now, when trying to run powerSim and powerCurve, this always produces errors. It can all very well be my faulty model, etc., but I talked to a colleague about it who suggested that simr might not support clmms in general.
Could you help?

Many many thanks in advance!

Best regards,
Carl

**Comment by pitakakariki** [comment]
Your colleague is correct - currently the only supported models are from `lm`, `glm`, `lmer`, and `glmer`.

**Comment by carlmenzies** [comment]
Many thanks for clearing this up so quickly!
