### ISSUE TITLE
Power estimates change when variables are Z-scored

### ISSUE THREAD

**Issue by lucindasisk** [pitakakariki/simr#244]
Hi! First off, thanks so much for your work creating and maintaining this package--it is an amazing resource! I was aiming to fit a relatively simple model with simulated data but found that the power estimates changed when I z-scored the variables. Would you happen to have insight on what might be going on here? Thanks so much for any help! Here is a reproducible example:

```
## Without standardization
data(iris)

example_lm <- eval(parse(text="glm(Sepal.Length~Species + Sepal.Width + Petal.Width, 
              data=iris, 
              family='gaussian')"))
summary(example_lm)

coef(example_lm)["Speciesversicolor"] <- 0.3 #Change approximate effect size

powerSim(example_lm, test = fixed("Speciesversicolor", method = "t"), nsim=100, 
         progress=TRUE, seed=0)

#Power for predictor 'Speciesversicolor', (95% confidence interval):=======================|
#       19.00% (11.84, 28.07)
# 
# Test: t-test
# 
# Based on 100 simulations, (0 warnings, 0 errors)
# alpha = 0.05, nrow = 150

```

```
## With Standardization

iris_std <- iris %>% 
  mutate(Sepal.Length = scale(Sepal.Length, center=TRUE, scale = TRUE)) %>% 
  mutate(Sepal.Width = scale(Sepal.Width, center=TRUE, scale = TRUE)) %>% 
  mutate(Petal.Width = scale(Petal.Width, center=TRUE, scale = TRUE))

example_lm2 <- eval(parse(text="glm(Sepal.Length~Species + Sepal.Width + Petal.Width, 
              data=iris_std, 
              family='gaussian')"))
summary(example_lm2)

coef(example_lm2)["Speciesversicolor"] <- 0.3 #Change approximate effect size

powerSim(example_lm2, test = fixed("Speciesversicolor", method = "t"), nsim=100, 
         progress=TRUE, seed=0)

# Power for predictor 'Speciesversicolor', (95% confidence interval):=======================|
#      12.00% ( 6.36, 20.02)
#
# Test: t-test
#
# Based on 100 simulations, (0 warnings, 0 errors)
# alpha = 0.05, nrow = 150




```

**Comment by pitakakariki** [comment]
You've scaled the response variable `Sepal.Length` as well as the predictors. This means that your effect size of 0.3 has a different meaning in the two examples.

**Comment by lucindasisk** [comment]
I see, thanks so much for your help!

**Comment by pitakakariki** [comment]
While you're here - I'm curious about the code idiom:

    example_lm <- eval(parse(text="glm(Sepal.Length~Species + Sepal.Width + Petal.Width, 
              data=iris, 
              family='gaussian')"))

Was there any reason it couldn't be simply:

    example_lm <- lm(Sepal.Length ~ Species + Sepal.Width + Petal.Width, data=iris)

**Comment by lucindasisk** [comment]
Ah, that was an artefact from sifting through the posts on Github and seeing someone encountering an issue that could be worked around using the eval/parse/text arguments. It runs both ways for me, though. Thanks again!
