### ISSUE TITLE
Complex models are not correctly deparsed

### ISSUE THREAD

**Issue by tr-rebholz** [pitakakariki/simr#250]
Complex models are not correctly deparsed (e.g., in simr::fcompare()) because formulas are broken into character vectors of size larger than one due to usage of deparse() instead of deparse1(). Consequently, fcomparing models is restricted/biased to the formula parts smaller or equal to the default character size 60L of deparse().

**Comment by pitakakariki** [comment]
Thanks, `deparse1` should make this easy to fix.

**Comment by tr-rebholz** [comment]
I just created a pull request

**Comment by pitakakariki** [comment]
Fixed: https://github.com/pitakakariki/simr/pull/254
