### ISSUE TITLE
Question about 'tests: Specify a statistical test to apply': "fixed" and "fcompare"

### ISSUE THREAD

**Issue by MenglinWuu** [pitakakariki/simr#255]
Hi there,
In the mannual of 'tests: Specify a statistical test to apply', detail goes:
> `fixed:` Test a single fixed effect, specified by xname.
> `fcompare`, `rcompare`: Similar to compare, but only the fixed/random part of the formula needs to be supplied.

, which is a little bit vague.

Taken  `mod <- lmer(y~A*B+(A+B|ID))` as an example, and we were interested in variable `A`. 
We would run `powerSim(mod, nsim=100, test = ....)` ,
Holding other parameters same, what is the difference among `test=fixed("A")` , `test=fcompare(".~B")` , and `test=fcompare(".~B+A:B")`?
Are they represent the same thing? Which test is the most appropriate? Is there any suitable conditions for a specific test generally? Or just depends on researchers?

Any clarify is greatly appreciated!

**Comment by pitakakariki** [comment]
`fixed("A")` will test the main effect of `A`. Note that you will likely get warnings about testing a main effect in the presence of interactions.

`fcompare(~B)` will compare the full model to the model without `A` and `A:B` which could be interpreted as a simultaneous test of both the main effect `A` and the interaction `A:B`.

`fcompare(~B+A:B)` is similar to `fixed("A")` but will use a different test by default. Note that `fixed("A", "kr")` and `fcompare(~B+A:B, "kr")` should give the same answer.

Which test to use will depend on the research question and is best discussed with a statistician.

**Comment by MenglinWuu** [comment]
Thanks! That helps a lot!
