### ISSUE TITLE
how to do the sensitivity analysis?

### ISSUE THREAD

**Issue by lovelyjerry666** [pitakakariki/simr#259]
I did a prior power analysis to calculate the sample size, and then the reviewer proposed to do another sensitivity analysis, but I looked up the literature, and didn't quite understand the meaning of sensitivity analysis. What do its results represent? And how do you do sensitivity analysis? Can someone help me with it?

**Comment by pitakakariki** [comment]
This issue tracker is not for general statistics queries. I can't help you with this.
