### ISSUE TITLE
Changing fixed effect

### ISSUE THREAD

**Issue by FrVitale** [pitakakariki/simr#273]
Hi,
I am conducting a power analysis using the following code:
```
pa_all<-powerSim(all_mix_out, nsim=1000, test=fcompare(RT~CONTENIDO*DIRECTION*Movimiento))
pa_all
This analysis is based on the model:
all_mix_out<-lmer(RT ~ CONTENIDO*GROUP*DIRECTION*Movimiento + (1|SUBJECT) , data = datos_outlier)
```

In the model, the fixed effect estimate for the interaction `CONTENIDOSocial:DIRECTIONEvit:MovimientoDetrás` interaction is -8.527. 

I know that if I want to change such value I can use this code:
```
fixef(all_mix_out)["CONTENIDOSocial:DIRECTIONEvit:MovimientoDetrás"] <- 
```
and assigne a specific value. 
Now, I would like to adjust this value to reflect a small or medium effect size? Could someone please advise me on what estimate value I should assign for this interaction?

Thank you for your assistence

**Comment by pitakakariki** [comment]
Unfortunately the appropriate effect size will depend on the particular goals of your study, and is not something I can assist you with.
