### ISSUE TITLE
simulated dataset

### ISSUE THREAD

**Issue by JJ-Zhang-DS** [pitakakariki/simr#281]
Hi there,

I am wondering if I can output the simulated datasets after simulation. After simulation, is it possible to store the data somewhere or output them? 
I am asking because the power is always close to 100%, so we want to check the simulation dataset to figure out. 

Thank you for supporting.

**Comment by pitakakariki** [comment]
`powerSim` and `powerCurve` don't store them, but you can use `doSim` to access a single simulation.

**Comment by JJ-Zhang-Bayer** [comment]
Thank you.
Looks like doSim only outputs the values for response variable. Is there a way to get the predictor values simultaneously? The whole data frame. 
I appreciate your supporting.

**Comment by pitakakariki** [comment]
No, but the predictor values don't change so you can just use e.g. `df$y <- doSim(model)`.

**Comment by JJ-Zhang-Bayer** [comment]
Yes, just realized that the predictors are fixed during simulation. 
thank you.
