### ISSUE TITLE
Helpful error messages

### ISSUE THREAD

**Issue by pitakakariki** [pitakakariki/simr#33]
Every error message a user gets should be helpful. For example, no nonsense about closures because a function was supplied when a `merMod` was expected.

This means more pre-emptive checks in the top-level functions.

e.g.:

- [ ] "subscript out of bounds" for fixed effects that don't exist
- [ ] proper message when `fcompare`/`rcompare` used on a model without random effects.

**Comment by CurtKnudsen** [comment]
I am unable to get simr to load, getting the following error messages related to sigma which should be exported from lme4:

> library("simr", lib.loc="C:/Program Files/R/R-3.3.0/library")
Loading required package: lme4
Loading required package: Matrix
Error : object ‘sigma’ is not exported by 'namespace:lme4'
Error: package or namespace load failed for ‘simr’

I'm using R version 3.3.0 (2016-05-03). I've tried reinstalling lme4, Matrix and simr but that did not fix the problem. The error message isn't that helpful.

**Comment by pitakakariki** [comment]
This is a problem with the `RLRsim` package.

The S3 method `sigma` was moved from `lme4` to `stats` in 3.3.0. If you have a windows binary for `RLRsim` built under R < 3.3.0, then the package looks for `sigma` in the wrong place. Source builds should be fine. 

Reinstalling `RLRsim` should fix this problem.

**Comment by mspitzer19** [comment]
I am trying to estimate the power of an interaction term and have trouble using the extend function. 

my model is

model = lmer(RT ~ TaskTransition + (1|ID), data)

and I would like to extend the model by the random intercept "ID" from n = 30 to n = 60.

somehow the powerSim function only gives me errors when i do 

model2 = extend(model1, along = "ID", n = 50)

 powerSim(model2, fixed("TaskTransition"), nsim = 500 )

What am I doing wrong. Somehow I can not find a good description on the internet. 

Thanks
Markus

**Comment by pitakakariki** [comment]
I'll need to know what errors you're getting. Is there anything in `lastResult()$errors`?

**Comment by mspitzer19** [comment]
> a3 = extend(a2, along = "ID", n = 50)
> doTest(a3, fixed("TaskTransition1:featureCorrelation1"),nsim = 500)
p-value for predictor 'TaskTransition1:featureCorrelation1': 0.0350661
          --------------------
Test: t-test
      Effect size for TaskTransition1:featureCorrelation1 is 0.068
> coef(a3)["TaskTransition1:featureCorrelation1"] = -0.07
> doTest(a3, fixed("TaskTransition1:featureCorrelation1"),nsim = 500)
p-value for predictor 'TaskTransition1:featureCorrelation1': 0.03029183
          --------------------
Test: t-test
      Effect size for TaskTransition1:featureCorrelation1 is -0.070
> powerSim(a3, fixed("TaskTransition1:featureCorrelation1"),nsim = 500)
Power for predictor 'TaskTransition1:featureCorrelation1', (95% confidence interval):
       0.00% ( 0.00,  0.74)

Test: t-test
      Effect size for TaskTransition1:featureCorrelation1 is -0.070

Based on 500 simulations, (0 warnings, 500 errors)
alpha = 0.05, nrow = 200

Time elapsed: 0 h 0 m 2 s
> ps <- lastResult()
> ps$errors
      stage index                 message
1   Testing     1 subscript out of bounds
2   Testing     2 subscript out of bounds
3   Testing     3 subscript out of bounds
4   Testing     4 subscript out of bounds

**Comment by mspitzer19** [comment]
I also get this error:

a = lmer(RT ~  featureCorrelation + (1|ID),  data = subset(dd, blockID !=3))
> e =extend(a, along = "ID", n = 50)
> doTest(e, test= fixed("featureCorrelation1"), nsim = 100)
Error in drop1.merMod(fit, dropname, test = "user", sumFun = fun, ...) : 
  scope is not a subset of term labels

**Comment by mspitzer19** [comment]
Oh I fixed the bug from the second e mail
but now i get this:

100 mismatch between 'beta' parameter vector names and internal names ((Intercept),featureCorrelationF)

**Comment by pitakakariki** [comment]
Not sure exactly what's happening there. Are you able to email you data and script to me so I can have a proper look at it tonight?

**Comment by mspitzer19** [comment]
Sure, 
I would like to extend the dataset along "ID" and then calculate the power for the interaction terms and plot a power curve. Also in general I was not able to just extend the dataset along ID with just one fixed effect factor (e.g. lmer(log_RT ~ TaskTransition + (1 | ID),data)).

I hope the dataset is fine for you. 

Thanks

Markus

**Comment by pitakakariki** [comment]
Unfortunately contrasts aren't supported yet in simr. I've opened an issue for this:
 https://github.com/pitakakariki/simr/issues/76.

Are you able to run your analyses with the default dummy encoding?

**Comment by pitakakariki** [comment]
Alternatively, install the latest version from github, which has a first pass at supporting contrasts.

**Comment by mspitzer19** [comment]
so it includes the contrasts with the new version?

**Comment by pitakakariki** [comment]
I added some code last night that takes any contrasts assigned to the original data frame, and attempts to transfer them to the extended data frame. Hopefully that should be enough to work in most cases, but it hasn't been thoroughly tested.

**Comment by mspitzer19** [comment]
Hey, was the extend function that supports contrasts tested yet?

Thanks
Markus

**Comment by pitakakariki** [comment]
As far as I can tell it's working, but I'm not sure when I'll have time to test it properly.

**Comment by mspitzer19** [comment]
A few other questions came up today: Is it possible to modulate the residual error or the covariances? 

Or the standard error of the estimate?

Thanks

**Comment by pitakakariki** [comment]
There's a help file under `?modify` with functions to alter residual error and random effect covariances.

There's no function to directly change the standard errors of the estimates, since these are implicit results of the design, residual error, etc.

**Comment by liznecka** [comment]
When I try to make a merMod object using makeGlmer, I get the warning message "In rpois(nsim * length(ftd), ftd) : NAs produced" and over half of the rows in the data for my merMod object have NA as the value for the dependent variable.  I'm assuming this is an error passed on from the simulate function, but I have no idea what it means or how to troubleshoot it.  Do you have advice?

Thanks!

**Comment by pitakakariki** [comment]
What sort of values are you getting for `fitted` on your model?

**Comment by liznecka** [comment]
Really variable answers - ranging from 0 all the way up to 2e9... I'll send you my model as an RData file via email.

`count(fitted(model1))

1   1.572142e-06    2
2   6.435151e-06    2
3   2.517454e-04    2
4   3.271967e-04    2
5   2.830783e-03    2
6   1.049145e-02    2
7   1.272432e-02    2
8   3.597149e-02    2
9   4.031172e-02    2
10  4.181439e-02    2
11  7.302776e-02    2
12  7.807332e-02    2
13  2.306155e-01    2
14  9.643132e-01    2
15  1.471155e+00    2
16  5.343708e+00    2
17  6.455072e+00    2
18  7.087231e+00    2
19  8.607689e+00    2
20  9.757583e+00    2
21  1.440779e+01    2
22  2.212698e+01    2
23  2.516000e+01    2
24  2.630605e+01    2
25  3.379772e+01    2
26  5.460187e+01    2
27  8.716622e+01    2
28  1.154268e+02    2
29  1.348370e+02    2
30  1.576578e+02    2
31  1.659514e+02    2
32  1.746814e+02    2
33  1.838706e+02    2
34  1.935432e+02    2
35  2.020527e+02    2
36  2.037246e+02    2
37  2.144416e+02    2
38  2.257224e+02    2
39  4.777624e+02    2
40  5.997601e+02    2
41  6.829040e+02    2
42  1.033644e+03    2
43  1.813513e+03    2
44  1.944096e+03    2
45  6.271071e+03    2
46  1.195446e+04    2
47  1.290457e+04    2
48  1.774380e+04    2
49  1.978606e+04    2
50  2.077305e+04    2
51  2.566501e+04    2
52  2.775051e+04    2
53  3.891177e+04    2
54  4.105497e+04    2
55  4.636681e+04    2
56  4.974926e+04    2
57  7.883693e+04    2
58  8.288133e+04    2
59  8.727234e+04    2
60  8.962755e+04    2
61  9.115038e+04    2
62  1.040419e+05    2
63  1.655163e+05    2
64  1.729801e+05    2
65  2.367041e+05    2
66  3.371650e+05    2
67  3.820804e+05    2
68  9.875534e+05    2
69  1.105218e+06    2
70  1.777302e+06    2
71  2.172484e+06    2
72  3.738471e+06    2
73  3.811337e+06    2
74  3.822378e+06    2
75  4.273654e+06    2
76  5.424038e+06    2
77  6.186484e+06    2
78  8.256639e+06    2
79  9.509441e+06    2
80  9.708649e+06    2
81  1.115305e+07    2
82  1.152579e+07    2
83  1.321963e+07    2
84  1.421166e+07    2
85  1.948927e+07    2
86  2.650395e+07    2
87  2.707688e+07    2
88  2.717197e+07    2
89  4.442391e+07    2
90  4.571984e+07    2
91  4.609463e+07    2
92  5.755809e+07    2
93  8.000832e+07    2
94  8.049871e+07    2
95  9.836998e+07    2
96  1.172735e+08    2
97  1.241848e+08    2
98  1.258073e+08    2
99  1.581213e+08    2
100 1.656850e+08    2
101 1.703653e+08    2
102 1.756752e+08    2
103 2.003735e+08    2
104 2.682054e+08    2
105 3.150823e+08    2
106 4.902110e+08    2
107 5.037102e+08    2
108 5.234602e+08    2
109 5.468596e+08    2
110 5.630270e+08    2
111 6.728025e+08    2
112 8.232672e+08    2
113 1.177006e+09    2
114 1.425314e+09    2
115 1.891304e+09    2
116 1.897519e+09    2
117 1.931619e+09    2`

**Comment by pitakakariki** [comment]
Because of the log link, Poisson models can explode if the linear predictor gets too big (because the inverse link is exponential).

```
> cbind(1:25, rpois(25, exp(1:25)))
      [,1]       [,2]
 [1,]    1          1
 [2,]    2          6
 [3,]    3         18
 [4,]    4         55
 [5,]    5        134
 [6,]    6        422
 [7,]    7       1124
 [8,]    8       3082
 [9,]    9       8162
[10,]   10      22043
[11,]   11      59854
[12,]   12     163439
[13,]   13     442598
[14,]   14    1201978
[15,]   15    3270323
[16,]   16    8888163
[17,]   17   24154937
[18,]   18   65661762
[19,]   19  178483214
[20,]   20  485171966
[21,]   21 1318870521
[22,]   22         NA
[23,]   23         NA
[24,]   24         NA
[25,]   25         NA
Warning message:
In rpois(25, exp(1:25)) : NAs produced
```

If you look at `fixef` and `coef` for your model, it looks like the values are unrealistically large?

**Comment by liznecka** [comment]
yes the values are definitely unrealistically large.  I just don't understand what about my model is producing this error.
