### ISSUE TITLE
Return effect size measures for observed power calculations

### ISSUE THREAD

**Issue by Ax3man** [pitakakariki/simr#67]
I might be nice to give effect sizes as Cohen's d and Pearson's r when running `powerSim`, since these have a intuitive interpretation. One can use the following paper as a source of how to calculate effect sizes for mixed models:

Nakagawa S, Cuthill IC. 2009. Effect size, confidence interval and statistical significance: A practical guide for biologists. Biol Rev 84: 515. 

For example, below are R functions for the calculation of Cohen's d for a linear mixed model with a categorical (2 levels) effect of interest (following the paper above). I have R functions for glmms and continuous variables as well, and could possibly spare some time to help out with implementation.

```
d.mix <- function(t.val, ni, no, no1, no2, k, R){
  d <- (t.val * (1 + (ni / no) * R) * sqrt(1 - R) * (no1 + no2)) /
    (sqrt(no1 * no2) * sqrt(no - k))
  names(d) <- "effect size d"
  return(d)
}
```

with:
```
R <- function(s2b, s2e) { #Equation 23
  R <- s2b / (s2b + s2e)
  names(R) <- "Repeatablity (ICC)"
  return(R)
}
```

**Comment by pitakakariki** [comment]
There's a follow-up by Johnson extending this to random slope models: http://onlinelibrary.wiley.com/doi/10.1111/2041-210X.12225/full

**Comment by pitakakariki** [comment]
I think the r-squared calculations might already be available in a couple of packages, `MuMIn` and `r2glmm`.

**Comment by pitakakariki** [comment]
I do have some reservations about reporting the Cohen's d type of effect sizes (i.e. standardised rather than simple effect sizes). There's a good summary here: http://www.floppybunny.org/robin/web/virtualclassroom/stats/basics/articles/effect_size/effect_size_baguley_2009.pdf

**Comment by Ax3man** [comment]
Ok, that's clear, fair enough. The issue can be closed, I would say. 

One final suggestion:

You can change a coefficient/effect size in the model using `fixef<-`. But I don't see an easy way to create a power curve with different coefficients, other than building a list of models yourself and running `powerSim` on each (which works fine).

These simulation can be useful when discussing negative results in publications, where you want to evaluate what size of an effect you would have reasonably been able to detect. (I realize there are some problems with post-hoc power analysis as well, but they are often asked for.)
